from tdm.commands.add import add
from tdm.commands.deploy import deploy
from tdm.commands.fork import fork
from tdm.commands.git import git
from tdm.commands.init import init
from tdm.commands.merge import merge
from tdm.commands.patch import patch
from tdm.commands.rejoin import rejoin
from tdm.commands.rm import rm
from tdm.commands.status import status
from tdm.commands.tree import tree
from tdm.commands.update import update
from tdm.commands.use import use
from tdm.commands.vacate import vacate
