from tdm.commands.add import add
from tdm.commands.deploy import deploy
from tdm.commands.fork import fork
from tdm.commands.init import init
from tdm.commands.patch import patch
from tdm.commands.rejoin import rejoin
from tdm.commands.rm import rm
from tdm.commands.use import use
from tdm.commands.vacate import vacate
